# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45b03579f5eba3d19e6d8d2b6de2570e60e8b87d53f737277f08cdd61fb2ddbec48b158e1a2f3a0a7c22efaf5a5cf162308d75094451f015618eaa072110f325

test:
  secret_key_base: eb019e1bf83db338f34c866e72844410dc5c8dcf7262c2e2cb0f5edf52ffdc137b31f92789865f128e7dd94f4c133ed74d45a301a1eeb7909f9dae998d8bfa6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
